### ISSUE TITLE
Disable debug logs

### ISSUE THREAD

**Issue by Androz2091** [Terisback/discord.v#5]
Hello :wave:
First of all, thank you for building this library (I started to make one myself then I saw this lib 😄)

I saw the comment in discord.v/util/log.v, "Remove then release". I think logs should be kept for debugging purposes, but it would be nice to be able to disable them (maybe using a DV_DEBUG environment variable or something like that?).

Thank you

**Comment by Terisback** [comment]
Yes, I'll add a debug flag. This was the original idea)
This issue refers to item from TODO, more "fancy" logs 

Thanks for using my lib)

**Comment by Terisback** [comment]
We can temporarily use the module log
What do you think?

**Comment by Androz2091** [comment]
> We can temporarily use the module log
What do you think?

Yes sure, they are sufficient 👍

**Comment by Terisback** [comment]
yep, I've implemented my [own log](https://github.com/Terisback/discord.v/blob/master/fancylog/log.v)
now it's somehow customizable.
Also, you can add [argument](https://github.com/Terisback/discord.v/blob/54fd45f616c6595f5cea1bd8d6b72dde8933148b/client.v#L45) `-d dv_debug` to change log level to `.debug` .

What do you think?

**Comment by Terisback** [comment]
Or is it better to use env variable?

**Comment by Terisback** [comment]
Can you reply? @Androz2091

**Comment by Androz2091** [comment]
Hello, it's still showing logs (such as `[discord.v] #0 Successfully connected to gateway`) without using `-d dv_debug` argument :thinking:

**Comment by Terisback** [comment]
forgot to set default log level to `.warn`
fixed in ef6b980

**Comment by Terisback** [comment]
@Androz2091 Fixed?

**Comment by Androz2091** [comment]
Yes, it works now 👍 
Thank you, should I close this issue?

**Comment by Terisback** [comment]
yep

**Comment by Androz2091** [comment]
@Terisback when running `v run codersbot.v -d dv_debug`, no logs are shown?

**Comment by Terisback** [comment]
@Androz2091 it's showing
![image](https://user-images.githubusercontent.com/26527529/104003610-71d29c80-51c4-11eb-94e3-8a5b3171ce6a.png)

**Comment by Androz2091** [comment]
Oh yes it works using -d before run
